/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package checkdb;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Moin
 */
public class eadd extends javax.swing.JFrame {

    /**
     * Creates new form eadd
     */
    public eadd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        eaa = new javax.swing.JTextArea();
        eid = new javax.swing.JTextField();
        enn = new javax.swing.JTextField();
        ecn = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Enter Employee ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(77, 38, 89, 14);

        jLabel2.setText("Enter Employee Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(77, 94, 105, 14);

        jLabel3.setText("Enter Employee Address");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(77, 178, 117, 14);

        jLabel4.setText("Enter Contact No ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(77, 250, 86, 14);

        eaa.setColumns(20);
        eaa.setRows(5);
        jScrollPane1.setViewportView(eaa);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(320, 140, 166, 83);
        getContentPane().add(eid);
        eid.setBounds(380, 30, 100, 20);
        getContentPane().add(enn);
        enn.setBounds(380, 90, 100, 20);
        getContentPane().add(ecn);
        ecn.setBounds(390, 250, 100, 20);

        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add);
        add.setBounds(240, 300, 83, 38);

        jLabel5.setIcon(new javax.swing.ImageIcon("E:\\Afreenproj\\windows-7-free-theme-download-abstract-theme.jpg")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 590, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        try {
            
            String empid = eid.getText();
            String ename = enn.getText();
            String eadd =eaa.getText();
            String econ=ecn.getText();
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/afproject", "root", "moin");
            String sql="insert into emp_details(emp_id, e_name, e_address, contact) "+"values (?, ?, ?, ?);";
            PreparedStatement ps=con.prepareStatement(sql);
         
            ps.setString(1,empid);
            ps.setString(2,ename);
            ps.setString(3,eadd);
            ps.setString(4,econ);
            ps.executeUpdate();   
            con.close();
            JOptionPane.showMessageDialog(null, "Data Inserted Sucessfully");
            //Statement st=con.createStatement();
            //ps.executeUpdate(sql);
        } catch (Exception ex) {
            
        }
    }//GEN-LAST:event_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(eadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(eadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(eadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(eadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new eadd().setVisible(true);
            }
        });
    }

    void setVisiable(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextArea eaa;
    private javax.swing.JTextField ecn;
    private javax.swing.JTextField eid;
    private javax.swing.JTextField enn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
