/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package checkdb;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Moin
 */
public class eupdate extends javax.swing.JFrame {

    /**
     * Creates new form eupdate
     */
    public eupdate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        eid = new javax.swing.JTextField();
        ess = new javax.swing.JTextField();
        esl = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        esa = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Enter Employee ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(69, 78, 89, 14);

        jLabel2.setText("Enter Employee Sales");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(69, 130, 103, 14);

        jLabel3.setText("Enter Employee leave");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 180, 104, 14);
        getContentPane().add(eid);
        eid.setBounds(370, 80, 75, 20);
        getContentPane().add(ess);
        ess.setBounds(370, 130, 75, 20);
        getContentPane().add(esl);
        esl.setBounds(370, 180, 75, 20);

        jLabel4.setText("Enter Employee Salary");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 230, 108, 30);
        getContentPane().add(esa);
        esa.setBounds(370, 230, 75, 20);

        update.setText("ADD");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(250, 300, 53, 23);

        jLabel5.setIcon(new javax.swing.ImageIcon("E:\\Afreenproj\\windows-7-free-theme-download-abstract-theme.jpg")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 570, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try {
            
            String empid = eid.getText();
            String esale = ess.getText();
            String eleave =esl.getText();
            String esala=esa.getText();
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/afproject", "root", "moin");
            String sql="insert into emp_data(emp_id, e_sales, e_leave, e_salary) "+"values (?, ?, ?, ?);";
            PreparedStatement ps=con.prepareStatement(sql);
         
            ps.setString(1,empid);
            ps.setString(2,esale);
            ps.setString(3,eleave);
            ps.setString(4,esala);
            ps.executeUpdate();   
            con.close();
            JOptionPane.showMessageDialog(null, "Data Inserted Sucessfully");
            //Statement st=con.createStatement();
            //ps.executeUpdate(sql);
        } catch (Exception ex) {
            
        }
    }//GEN-LAST:event_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(eupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(eupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(eupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(eupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new eupdate().setVisible(true);
            }
        });
    }

    void setVisiable(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField eid;
    private javax.swing.JTextField esa;
    private javax.swing.JTextField esl;
    private javax.swing.JTextField ess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
