/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package checkdb;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Moin
 */
public class salHome extends javax.swing.JFrame {

    /**
     * Creates new form salHome
     */
    public salHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Displaydetails = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        calculate = new javax.swing.JButton();
        eid = new javax.swing.JTextField();
        leave = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        profit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Displaydetails.setText("Display Details");
        Displaydetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplaydetailsActionPerformed(evt);
            }
        });
        getContentPane().add(Displaydetails);
        Displaydetails.setBounds(410, 150, 127, 50);

        jLabel1.setText("Enter Emp ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 70, 100, 14);

        jLabel2.setText("Enter Leaves");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 140, 100, 14);

        calculate.setText("Calculate  Salary");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });
        getContentPane().add(calculate);
        calculate.setBounds(120, 290, 126, 36);

        eid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eidActionPerformed(evt);
            }
        });
        getContentPane().add(eid);
        eid.setBounds(210, 60, 100, 30);

        leave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveActionPerformed(evt);
            }
        });
        getContentPane().add(leave);
        leave.setBounds(210, 130, 100, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Enter Profit");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 200, 90, 22);

        profit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profitActionPerformed(evt);
            }
        });
        getContentPane().add(profit);
        profit.setBounds(210, 200, 100, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon("E:\\Afreenproj\\windows-7-free-theme-download-abstract-theme.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 590, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DisplaydetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplaydetailsActionPerformed
        // TODO add your handling code here:
try
        {
          JTable table;
          Object data [][];
          PreparedStatement pst;
          JFrame f1 = new JFrame();
          f1.setSize(500,500);
          f1.setVisible(true);
          String col [] ={"emp_id","e_sales","e_leave","e_salary"};   
          DefaultTableModel model = new DefaultTableModel();
          model.setColumnIdentifiers(col);
          table = new JTable();
          table.setModel(model);
          table.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
          table.setFillsViewportHeight(true);
          
          JScrollPane scroll = new JScrollPane(table);
          scroll.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
          scroll.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
          
          int emp_id;
          String e_sales;
          String e_leave;
          String e_salary;
          
            Class.forName("com.mysql.jdbc.Driver");
            java.sql.Connection con=(java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/afproject", "root", "moin");
            pst = con.prepareStatement("select * from emp_data;");
            ResultSet rs=(com.mysql.jdbc.ResultSet) pst.executeQuery();
            
            while(rs.next())
                {
                        emp_id = rs.getInt("emp_id");
                        e_sales = rs.getString("e_sales");
                        e_leave =rs.getString("e_leave");
                        e_salary=rs.getString("e_salary");
                       
                        model.addRow(new Object[]{emp_id,e_sales,e_leave,e_salary});
                }
            rs.close();
            pst.close();
            con.close();
            f1.add(scroll);
        }
      
        catch(Exception e){
        }
    }//GEN-LAST:event_DisplaydetailsActionPerformed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        // TODO add your handling code here:
        
        int id = Integer.parseInt(eid.getText());
        int ele = Integer.parseInt(leave.getText());
        int profit =Integer.parseInt(this.profit.getText());
        int ns=0;
        int salary = 8000;
        if(ele >0)
        {
            if(profit >0)
            {
                profit = salary + 200 * profit;
            }
            for(int i=0;i<=ele;i++)
            {
                ns = profit - 300 * i ;
            }
            JOptionPane.showMessageDialog(null, "Salary with no of leaves :"+ele+" is "+ns);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "No Leaves Therefore Salary is : "+salary);
        }
        
    }//GEN-LAST:event_calculateActionPerformed

    private void eidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eidActionPerformed

    private void leaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leaveActionPerformed

    private void profitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(salHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(salHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(salHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(salHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new salHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Displaydetails;
    private javax.swing.JButton calculate;
    private javax.swing.JTextField eid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField leave;
    private javax.swing.JTextField profit;
    // End of variables declaration//GEN-END:variables
}
